### ISSUE TITLE
Attribution Windows

### ISSUE THREAD

**Issue by KrisM-tor** [Deducive/FBinsightsR#1]
Hi there, this question may be a bit ambiguous - but I was wondering if it's possible to include attribution windows as a parameter to pulling results? I don't have much experience integration additional API commands in R unfortunately

Thanks!

**Comment by paulnewnes** [comment]
Hi. Thanks for the note. I’ll take a look and see if it’s something that can be integrated.

**Comment by KrisM-tor** [comment]
Great thank you! Is it difficult to introduce new components of the API? Is it literally just a matter of building it into the function in the functions.R file?

**Comment by paulnewnes** [comment]
I'm not too familiar with how Facebook's attribution window is calculated and whether it requires a different input from the other ad-insights features. Seems like it could exist temporally separately from other metrics. Hence I need to research first.

**Comment by paulnewnes** [comment]
Hence, I need to research first.

**Comment by KrisM-tor** [comment]
I see - a separate issue that I'm having at the moment is the following:

" WWW-Authenticate: OAuth "Facebook Platform" "invalid_request" "(#272) This Ads API call requires the user to be admin of the application. User is not admin or developer of this application."

I've been elevated to admin level almost everywhere but it seems to not be letting me through. Do I need to create an "app" on the account?

On the facebook graph API page I'm selecting "get user token" and choosing version 2.12

Thanks for all the help!
-Kris

**Comment by paulnewnes** [comment]
yes - you need an app with the appropriate permissions. It doesn't need to
be approved or anything.

**Comment by KrisM-tor** [comment]
I really appreciate your patience on this haha - okay so I've made an "app" and am in the "marketing API" section of it. The Business Manager portion asks me to associate the business account with the "app" but unfortunately I require a business manager to let it through. This should allow me sufficient access correct? 

Also is the package compatible with the latest API version of v3.0? I noticed the version 2.12 is referenced in the function

**Comment by paulnewnes** [comment]
I don't have that level of knowledge around business accounts, versus non
business accounts - so can' t assist on that. API version should be fine -
we'll be updating to the latest version in time.

**Comment by KrisM-tor** [comment]
Does this package still work for you? I encounter the following:

"<- WWW-Authenticate: OAuth "Facebook Platform" "invalid_request" "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.0.""

**Comment by paulnewnes** [comment]
the package still works for me. API version is 2.12 which is still
supported. I'll update in due course, but the latest version still
functions. Maybe your app or token is for 3.0 only.

**Comment by KrisM-tor** [comment]
Yes the token is 3.0 - unfortunately it doesn't look like I can revert the "application" token to anything but v3.0.. The personal user access token let's me select any version, but that unfortunately doesn't allow me entry into business insights

**Comment by paulnewnes** [comment]
API reference changed to 3.0

**Comment by KrisM-tor** [comment]
Amazing, it works perfectly! In terms of the variables that are requested from the API. Is it as simple as adding it in the source R package? Same thing with the attribution windows?



Thanks once again, your help has been greatly appreciated on this! (and saving me so much time)

**Comment by paulnewnes** [comment]
You’re welcome. For insights variables then those can be added in - you
should see where in the api call. However the majority, for ads, are
already there or can be calculated from those pulled.

For attribution windows, the little research I’ve done shows a little more
complication to how this could be added to the package. I’m loathed to add
another input argument to the existing functions.  I still need to fully
understand how the returned results change with different windows
specified.

Again, thanks for using the package and your feedback.

**Comment by KrisM-tor** [comment]
One more question for you, how do you extend the API token beyond one day?

Edit: I've found a solution for this - thanks once again

**Comment by paulnewnes** [comment]
Thanks - on the tokens - you can use the token debugger to get a long lived token, or there's an API method also.

**Comment by KrisM-tor** [comment]
Hi Paul - was just wondering if you've encountered this situation. I have a few custom conversion variables that I'm able select via the column selector in Facebook's reporting tool, but am unsure how to select these columns within the API (the fields section to be exact). The documentation from Facebook unfortunately is not very clear and pushes towards variables that roll up ALL conversions in my campaign.


thank you

**Comment by paulnewnes** [comment]
Hi - not something I've investigated nor really come across unfortunately.
