### ISSUE TITLE
fbins_summ get Error

### ISSUE THREAD

**Issue by Bustami** [Deducive/FBinsightsR#2]
Hi!
I'm trying to download insight data but i get an error:

Error: `.x` is empty, and no `.init` supplied

> -> Host: graph.facebook.com
-> User-Agent: libcurl/7.59.0 r-curl/3.2 httr/1.3.1
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> 
<- HTTP/1.1 404 Not Found
<- Access-Control-Allow-Origin: *
<- x-app-usage: {"call_count":0,"total_cputime":0,"total_time":0}
<- Strict-Transport-Security: max-age=15552000; preload
<- x-fb-trace-id: C9CFioajTnU
<- x-fb-rev: 4114448
<- Content-Type: application/json; charset=UTF-8
<- facebook-api-version: v3.0
<- Cache-Control: no-store
<- Pragma: no-cache
<- Expires: Sat, 01 Jan 2000 00:00:00 GMT
<- WWW-Authenticate: OAuth "Facebook Platform" "not_found" "(#803) Some of the aliases you requested do not exist: act_yalealanguages"
<- Vary: Accept-Encoding
<- Content-Encoding: gzip
<- X-FB-Debug: YTh0J1L/hCexpZj3G+nVa0Ar9aIbxpjdFgP00xcisYEW17XzSdgB6a4puArUpcRRQ2g8wBJlZhgplwJEhvejxg==
<- Date: Wed, 18 Jul 2018 19:22:10 GMT
<- Connection: keep-alive
<- Content-Length: 157
<- 
Error: `.x` is empty, and no `.init` supplied

Do you have an idea about this?

**Comment by paulnewnes** [comment]
Can you paste the function code (with obscured token and account number)
here please.

**Comment by Bustami** [comment]
sure:

`
start_date <- '2018-06-01'

until_date <- '2018-06-30'

report_level <- 'campaign'

time_increment <- '1'

fbins_summ(start_date, until_date, report_level, time_increment, fb_access_token, fb_ad_account)`

**Comment by paulnewnes** [comment]
Hi - firstly, the package works fine for me - just tested.

<- WWW-Authenticate: OAuth "Facebook Platform" "not_found" "(#803) Some of the aliases you requested do not exist: act_yalealanguages"
<- Vary: Accept-Encoding
<- Content-Encoding: gzip

I replicated the error message. Are you sure your ad account number is correct? It should be in the exact format of "act_12345678901234" retrievable from the Ads Manager screen. Everything after the underscore is numeric, always.

I'm also assuming you have an app token (having set up an app) and that it has the required permissions and that the app is fine with API v3.0.

Thanks.

**Comment by Bustami** [comment]
good! Now it's working for me also.

I've been naming the 'fb_ad_account' parameter with the real name of page (character), and not with the numeric id.

Thank you so much dude!
