### ISSUE TITLE
Can this be used to extract Facebook Page Insights data from a Business Page?

### ISSUE THREAD

**Issue by BrisbanePom** [Deducive/FBinsightsR#5]
I have a business page that I like to analyse the data from. Traditionally I would go to the Insights tab on the Business Page and click the Export Data button, downloading the data into an Excel spresdsheet.  This I can then ingest into R (specific tabs - there are a lot of them!) to explore / visualise the data (e.g. likes per day by source / region etc).
Can this package be used to replicate that function, or is it limited to tracking the result of paid ads only?

**Comment by paulnewnes** [comment]
If you check the wiki, there’s a description of the function to pull page insights.
